name: Node CI

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [6, 8]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
